server:
  port: 8082
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/text
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    #prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30 #每隔30秒向服务器续约一次心跳
    lease-expiration-duration-in-seconds: 90 #90秒以后还没法心跳，那就说明你挂了
    #ip-address: 127.0.0.1
mybatis:
  type-aliases-package: cn.itcast.user.pojo