server:
  port: 10086

spring:
    application:
      name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-with-eureka: false #启动时要不要注册自己
  server:
    eviction-interval-timer-in-ms: 60000 #剔除失效的服务，默认为60秒剔除一次
    enable-self-preservation: true #保护机制 eureka会统计服务实例最近15分钟的心跳续约比例是否低于85%，低于就剔除


